# Generated by Django 3.2 on 2021-04-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
